/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import ManejoDeArchivo.ManejoArchivos;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author elian
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        LabelIniciarSesion = new javax.swing.JLabel();
        LabelTituloUsuario = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTituloContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        icono1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        icono2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(300, 400));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelIniciarSesion.setText("INICIAR SESIÓN");
        bg.add(LabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 50));

        LabelTituloUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTituloUsuario.setText("USUARIO");
        bg.add(LabelTituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Usuario.setForeground(new java.awt.Color(153, 153, 153));
        Usuario.setBorder(null);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        bg.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 30));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 20));

        LabelTituloContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTituloContraseña.setText("CONTRASEÑA");
        bg.add(LabelTituloContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 20));

        icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User (1).png"))); // NOI18N
        bg.add(icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 80, -1));

        icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/depositphotos_718231796-stock-illustration-gym-high-quality-vector-logo.jpg"))); // NOI18N
        bg.add(icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -60, 360, 490));

        btnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setFocusPainted(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        bg.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 30));

        Contraseña.setForeground(new java.awt.Color(153, 153, 153));
        Contraseña.setBorder(null);
        bg.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 30));
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    
     String LoginIngresado = Usuario.getText();
     String ContraseñaIngresada = Contraseña.getText();
     
     try {
        ManejoArchivos M = new ManejoArchivos();
        File Archivo = new File("Usuarios.txt");
        String loginIngresado = Usuario.getText().trim();
        String contraseñaIngresada = Contraseña.getText().trim();

        String cadenaA = M.buscar(loginIngresado, Archivo);

        if (cadenaA != null && !cadenaA.isEmpty()) {
            // Separar la línea usando "|"
            String[] datos = cadenaA.split("\\|");

            if (datos.length >= 4) {
                String LoginArchivo = datos[0];
                String ContraseñaArchivo = datos[2];
                String Nivel_Acceso = datos[3];

                if (LoginIngresado.equals(LoginArchivo)||contraseñaIngresada.equals(ContraseñaArchivo)) {
                    // Si la contraseña es correcta, damos acceso
                    JOptionPane.showMessageDialog(this, "Acceso permitido", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Mostrar el menú principal
                    Menu menu = new Menu(Nivel_Acceso);
                    menu.setVisible(true);
                    this.dispose(); // Cerrar la ventana de login

                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error en formato de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error en el formato del nivel de acceso.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  
  

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel LabelIniciarSesion;
    private javax.swing.JLabel LabelTituloContraseña;
    private javax.swing.JLabel LabelTituloUsuario;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel icono1;
    private javax.swing.JLabel icono2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
