/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Consultas.CUsuarios;
import Mantenimientos.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author elian
 */
public class Menu extends javax.swing.JFrame {

     public Menu() {
        initComponents(); // Constructor sin parámetros
    }
     
    public Menu(String Nivel_Acceso) {
        initComponents();
        setLocationRelativeTo(null);
        ConfigMenu(Nivel_Acceso);
       
        
    }
    private void ConfigMenu(String Nivel_Acceso){
    if (Nivel_Acceso.equals("1")) {
        jMenu_Mantenimientos.setEnabled(false);
        jMenu_Movimientos.setEnabled(false);
        jMenu_Procesos.setEnabled(false);
        jMenu_Consultas.setEnabled(false);
    } else if (!Nivel_Acceso.equals("1") && !Nivel_Acceso.equals("0")) {
        JOptionPane.showMessageDialog(null, "Nivel de Acceso No válido, debe ser 0 o 1");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_Mantenimientos = new javax.swing.JMenu();
        jmt_MantenimientoUsuario = new javax.swing.JMenuItem();
        jmt_MantenimientoEntrenador = new javax.swing.JMenuItem();
        jmt_MantenimientoLocalizacion = new javax.swing.JMenuItem();
        jmt_MantenimientoSalas = new javax.swing.JMenuItem();
        jmt_MantenimientoActividades = new javax.swing.JMenuItem();
        jmt_MantenimientoHorarioActividades = new javax.swing.JMenuItem();
        jmt_MantenimientoClientes = new javax.swing.JMenuItem();
        jmt_MantenimientoEstadoReserva = new javax.swing.JMenuItem();
        jmt_MantenimientoReserva = new javax.swing.JMenuItem();
        jmt_MantenimientoReservaActividades = new javax.swing.JMenuItem();
        jMenu_Movimientos = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu_Procesos = new javax.swing.JMenu();
        jm_ProcesosGenerarCobro = new javax.swing.JMenuItem();
        jm_ProcesosReservarCobro = new javax.swing.JMenuItem();
        jm_ProcesosActualizarCobro = new javax.swing.JMenuItem();
        jMenu_Consultas = new javax.swing.JMenu();
        jm_ConsultasUsuario = new javax.swing.JMenuItem();
        jm_ConsultasEntrenador = new javax.swing.JMenuItem();
        jm_ConsultasLocalizacion = new javax.swing.JMenuItem();
        jm_ConsultasSalas = new javax.swing.JMenuItem();
        jm_ConsultasActividades = new javax.swing.JMenuItem();
        jm_ConsultasHorariosActividades = new javax.swing.JMenuItem();
        jm_ConsultasCobroPorRangoDeFecha = new javax.swing.JMenuItem();
        jm_ConsultasCobroPorCliente = new javax.swing.JMenuItem();
        jm_ConsultasCuotaPorFecha = new javax.swing.JMenuItem();
        jm_ConsultasCuotaPorCliente = new javax.swing.JMenuItem();
        jm_ConsultasClientes = new javax.swing.JMenuItem();
        jm_ConsultasClientesPorBalancePendiente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga (1).jpeg"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga (2).jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu_Mantenimientos.setText("Mantenimientos ");

        jmt_MantenimientoUsuario.setText("De Usuario");
        jmt_MantenimientoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_MantenimientoUsuarioActionPerformed(evt);
            }
        });
        jMenu_Mantenimientos.add(jmt_MantenimientoUsuario);

        jmt_MantenimientoEntrenador.setText("De Entrenador");
        jmt_MantenimientoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_MantenimientoEntrenadorActionPerformed(evt);
            }
        });
        jMenu_Mantenimientos.add(jmt_MantenimientoEntrenador);

        jmt_MantenimientoLocalizacion.setText("De Localizacion");
        jMenu_Mantenimientos.add(jmt_MantenimientoLocalizacion);

        jmt_MantenimientoSalas.setText("De Salas");
        jMenu_Mantenimientos.add(jmt_MantenimientoSalas);

        jmt_MantenimientoActividades.setText("De Actividades");
        jMenu_Mantenimientos.add(jmt_MantenimientoActividades);

        jmt_MantenimientoHorarioActividades.setText("De Horario Activades");
        jMenu_Mantenimientos.add(jmt_MantenimientoHorarioActividades);

        jmt_MantenimientoClientes.setText("De Clientes");
        jMenu_Mantenimientos.add(jmt_MantenimientoClientes);

        jmt_MantenimientoEstadoReserva.setText("Estado de Reserva");
        jmt_MantenimientoEstadoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_MantenimientoEstadoReservaActionPerformed(evt);
            }
        });
        jMenu_Mantenimientos.add(jmt_MantenimientoEstadoReserva);

        jmt_MantenimientoReserva.setText("De Reserva");
        jMenu_Mantenimientos.add(jmt_MantenimientoReserva);

        jmt_MantenimientoReservaActividades.setText("Reserva Activadades");
        jmt_MantenimientoReservaActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmt_MantenimientoReservaActividadesActionPerformed(evt);
            }
        });
        jMenu_Mantenimientos.add(jmt_MantenimientoReservaActividades);

        jMenuBar2.add(jMenu_Mantenimientos);

        jMenu_Movimientos.setText("Movimientos      ");

        jMenuItem11.setText("Cuotas");
        jMenu_Movimientos.add(jMenuItem11);

        jMenuBar2.add(jMenu_Movimientos);

        jMenu_Procesos.setText("Procesos   ");

        jm_ProcesosGenerarCobro.setText("Generar Cobro");
        jm_ProcesosGenerarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ProcesosGenerarCobroActionPerformed(evt);
            }
        });
        jMenu_Procesos.add(jm_ProcesosGenerarCobro);

        jm_ProcesosReservarCobro.setText("Reservar Cobro");
        jMenu_Procesos.add(jm_ProcesosReservarCobro);

        jm_ProcesosActualizarCobro.setText("Actualizar Cobro");
        jm_ProcesosActualizarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ProcesosActualizarCobroActionPerformed(evt);
            }
        });
        jMenu_Procesos.add(jm_ProcesosActualizarCobro);

        jMenuBar2.add(jMenu_Procesos);

        jMenu_Consultas.setText("Consultas");

        jm_ConsultasUsuario.setText("De Usuario");
        jm_ConsultasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ConsultasUsuarioActionPerformed(evt);
            }
        });
        jMenu_Consultas.add(jm_ConsultasUsuario);

        jm_ConsultasEntrenador.setText("De Entrenador");
        jMenu_Consultas.add(jm_ConsultasEntrenador);

        jm_ConsultasLocalizacion.setText("De Localizacion");
        jMenu_Consultas.add(jm_ConsultasLocalizacion);

        jm_ConsultasSalas.setText("De Salas");
        jMenu_Consultas.add(jm_ConsultasSalas);

        jm_ConsultasActividades.setText("De Activades");
        jMenu_Consultas.add(jm_ConsultasActividades);

        jm_ConsultasHorariosActividades.setText("De Horarios Activades");
        jMenu_Consultas.add(jm_ConsultasHorariosActividades);

        jm_ConsultasCobroPorRangoDeFecha.setText("De Cobro Por Rango de Fecha");
        jMenu_Consultas.add(jm_ConsultasCobroPorRangoDeFecha);

        jm_ConsultasCobroPorCliente.setText("De Cobro Por Cliente");
        jMenu_Consultas.add(jm_ConsultasCobroPorCliente);

        jm_ConsultasCuotaPorFecha.setText("De Cuota Por Fecha");
        jMenu_Consultas.add(jm_ConsultasCuotaPorFecha);

        jm_ConsultasCuotaPorCliente.setText("De Cuota Por Cliente");
        jMenu_Consultas.add(jm_ConsultasCuotaPorCliente);

        jm_ConsultasClientes.setText("De Clientes");
        jMenu_Consultas.add(jm_ConsultasClientes);

        jm_ConsultasClientesPorBalancePendiente.setText("De Clientes Por Balance Pendiente");
        jMenu_Consultas.add(jm_ConsultasClientesPorBalancePendiente);

        jMenuBar2.add(jMenu_Consultas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmt_MantenimientoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_MantenimientoEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmt_MantenimientoEntrenadorActionPerformed

    private void jmt_MantenimientoEstadoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_MantenimientoEstadoReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmt_MantenimientoEstadoReservaActionPerformed

    private void jmt_MantenimientoReservaActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_MantenimientoReservaActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmt_MantenimientoReservaActividadesActionPerformed

    private void jm_ProcesosGenerarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ProcesosGenerarCobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_ProcesosGenerarCobroActionPerformed

    private void jm_ProcesosActualizarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ProcesosActualizarCobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_ProcesosActualizarCobroActionPerformed

    private void jmt_MantenimientoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmt_MantenimientoUsuarioActionPerformed
    Usuarios V = new Usuarios();
    V.setVisible(true);
    
       
        
    }//GEN-LAST:event_jmt_MantenimientoUsuarioActionPerformed

    private void jm_ConsultasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ConsultasUsuarioActionPerformed
    CUsuarios m = new CUsuarios();
    
    m.setVisible(true);

    }//GEN-LAST:event_jm_ConsultasUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenu jMenu_Consultas;
    private javax.swing.JMenu jMenu_Mantenimientos;
    private javax.swing.JMenu jMenu_Movimientos;
    private javax.swing.JMenu jMenu_Procesos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jm_ConsultasActividades;
    private javax.swing.JMenuItem jm_ConsultasClientes;
    private javax.swing.JMenuItem jm_ConsultasClientesPorBalancePendiente;
    private javax.swing.JMenuItem jm_ConsultasCobroPorCliente;
    private javax.swing.JMenuItem jm_ConsultasCobroPorRangoDeFecha;
    private javax.swing.JMenuItem jm_ConsultasCuotaPorCliente;
    private javax.swing.JMenuItem jm_ConsultasCuotaPorFecha;
    private javax.swing.JMenuItem jm_ConsultasEntrenador;
    private javax.swing.JMenuItem jm_ConsultasHorariosActividades;
    private javax.swing.JMenuItem jm_ConsultasLocalizacion;
    private javax.swing.JMenuItem jm_ConsultasSalas;
    private javax.swing.JMenuItem jm_ConsultasUsuario;
    private javax.swing.JMenuItem jm_ProcesosActualizarCobro;
    private javax.swing.JMenuItem jm_ProcesosGenerarCobro;
    private javax.swing.JMenuItem jm_ProcesosReservarCobro;
    private javax.swing.JMenuItem jmt_MantenimientoActividades;
    private javax.swing.JMenuItem jmt_MantenimientoClientes;
    private javax.swing.JMenuItem jmt_MantenimientoEntrenador;
    private javax.swing.JMenuItem jmt_MantenimientoEstadoReserva;
    private javax.swing.JMenuItem jmt_MantenimientoHorarioActividades;
    private javax.swing.JMenuItem jmt_MantenimientoLocalizacion;
    private javax.swing.JMenuItem jmt_MantenimientoReserva;
    private javax.swing.JMenuItem jmt_MantenimientoReservaActividades;
    private javax.swing.JMenuItem jmt_MantenimientoSalas;
    private javax.swing.JMenuItem jmt_MantenimientoUsuario;
    // End of variables declaration//GEN-END:variables
}
